-- Orden para que lo corras en workbench

-- #1
CREATE DATABASE GRADUATION_PROJECT;

-- #2
USE GRADUATION_PROJECT;

-- #3
CREATE TABLE USERS (
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR(50),
PASSWORD VARCHAR(50),
PHOTO VARCHAR(50)
);

-- #4
CREATE TABLE COMMENTS (
ID INT PRIMARY KEY auto_increment,
COMMENT VARCHAR(250),
USER_ID INT);

-- #5
ALTER TABLE COMMENTS ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);